language: python
python:
  - "2.7"
install:
    - pip install coveralls
# Prevent traceback printing for doctest to correctly run.
script:
  - coverage run test/test.py 2>/dev/null
after_success:
  - coveralls
